// ─── Styles ───────────────────────────────────────────────────────
export const S = {
  app: { fontFamily: '"Source Code Pro", "JetBrains Mono", monospace', background: 'var(--color-background-tertiary)', minHeight: '100vh', padding: 0 },
  header: { background: 'var(--color-background-primary)', borderBottom: '0.5px solid var(--color-border-tertiary)', padding: '12px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' },
  title: { fontSize: 16, fontWeight: 500, color: 'var(--color-text-primary)', letterSpacing: '-0.3px' },
  badge: { fontSize: 10, padding: '2px 8px', borderRadius: 'var(--border-radius-md)', background: 'var(--color-background-info)', color: 'var(--color-text-info)', fontWeight: 500, letterSpacing: '0.5px', textTransform: 'uppercase' },
  select: { fontSize: 12, padding: '6px 10px', borderRadius: 'var(--border-radius-md)', border: '0.5px solid var(--color-border-secondary)', background: 'var(--color-background-primary)', color: 'var(--color-text-primary)', cursor: 'pointer', outline: 'none', fontFamily: 'inherit' },
  btn: { fontSize: 11, padding: '6px 14px', borderRadius: 999, border: '0.5px solid var(--color-border-secondary)', background: 'var(--color-background-primary)', color: 'var(--color-text-primary)', cursor: 'pointer', fontWeight: 500, transition: 'all .15s', whiteSpace: 'nowrap', fontFamily: 'inherit' },
  btnPrimary: { background: 'var(--color-text-primary)', color: 'var(--color-background-primary)', border: 'none' },
  btnSuccess: { background: '#1D9E75', color: '#fff', border: 'none' },
  btnDanger: { background: 'var(--color-background-danger)', color: 'var(--color-text-danger)', border: '0.5px solid var(--color-border-danger)' },
  btnSmall: { fontSize: 10, padding: '3px 8px' },
  tabs: { display: 'flex', gap: 0, borderBottom: '0.5px solid var(--color-border-tertiary)', background: 'var(--color-background-primary)', padding: '0 16px' },
  tab: (active) => ({ fontSize: 12, padding: '10px 16px', cursor: 'pointer', border: 'none', background: 'none', color: active ? 'var(--color-text-primary)' : 'var(--color-text-secondary)', fontWeight: active ? 500 : 400, borderBottom: active ? '2px solid var(--color-text-primary)' : '2px solid transparent', transition: 'all .15s', fontFamily: 'inherit' }),
  panel: { padding: 16, background: 'var(--color-background-primary)', margin: 8, borderRadius: 'var(--border-radius-lg)', border: '0.5px solid var(--color-border-tertiary)' },
  canvas: { width: '100%', height: 480, borderRadius: 'var(--border-radius-lg)', border: '0.5px solid var(--color-border-tertiary)', cursor: 'default', background: 'var(--color-background-secondary)' },
  sidebar: { width: 280, minWidth: 280, padding: 12, background: 'var(--color-background-primary)', borderLeft: '0.5px solid var(--color-border-tertiary)', overflowY: 'auto', maxHeight: 480, fontSize: 12 },
  label: { fontSize: 11, color: 'var(--color-text-secondary)', marginBottom: 4, display: 'block', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.5px' },
  input: { fontSize: 12, padding: '5px 8px', borderRadius: 'var(--border-radius-md)', border: '0.5px solid var(--color-border-tertiary)', background: 'var(--color-background-secondary)', color: 'var(--color-text-primary)', width: '100%', boxSizing: 'border-box', outline: 'none', fontFamily: 'inherit' },
  chip: (active) => ({ fontSize: 10, padding: '2px 8px', borderRadius: 12, border: '0.5px solid', borderColor: active ? 'var(--color-border-info)' : 'var(--color-border-tertiary)', background: active ? 'var(--color-background-info)' : 'var(--color-background-secondary)', color: active ? 'var(--color-text-info)' : 'var(--color-text-secondary)', cursor: 'pointer', fontWeight: 500, transition: 'all .12s', whiteSpace: 'nowrap', userSelect: 'none' }),
  chipDanger: { fontSize: 10, padding: '2px 8px', borderRadius: 12, border: '0.5px solid var(--color-border-danger)', background: 'var(--color-background-danger)', color: 'var(--color-text-danger)', cursor: 'pointer', fontWeight: 500 },
  chipSuccess: (active) => ({ fontSize: 10, padding: '2px 8px', borderRadius: 12, border: '0.5px solid', borderColor: active ? 'var(--color-border-success)' : 'var(--color-border-tertiary)', background: active ? 'var(--color-background-success)' : 'var(--color-background-secondary)', color: active ? 'var(--color-text-success)' : 'var(--color-text-secondary)', cursor: 'pointer', fontWeight: 500, transition: 'all .12s', whiteSpace: 'nowrap', userSelect: 'none' }),
  row: { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  section: { marginBottom: 14 },
  divider: { borderTop: '0.5px solid var(--color-border-tertiary)', margin: '12px 0' },
  code: { fontSize: 11, fontFamily: 'var(--font-mono)', background: 'var(--color-background-secondary)', padding: '8px 12px', borderRadius: 'var(--border-radius-md)', overflowX: 'auto', whiteSpace: 'pre', maxHeight: 400, overflowY: 'auto', color: 'var(--color-text-primary)', border: '0.5px solid var(--color-border-tertiary)', lineHeight: 1.5 },
  toast: { position: 'fixed', bottom: 20, right: 20, padding: '10px 20px', borderRadius: 'var(--border-radius-md)', background: 'var(--color-text-primary)', color: 'var(--color-background-primary)', fontSize: 12, fontWeight: 500, zIndex: 999, fontFamily: 'inherit' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 },
  modal: { background: 'var(--color-background-primary)', borderRadius: 'var(--border-radius-lg)', padding: 24, minWidth: 320, maxWidth: 480, border: '0.5px solid var(--color-border-tertiary)' },
};